"""Derivative stage of the table pipeline and final six-column assembly.

Input: an amplitude table ``alpha,d,kappa,Ps[,status]`` on a log-uniform
``kappa`` axis (either freshly generated by ``vcdm_genesis.table`` or an existing
table whose ``Ps`` column must be preserved).  For every ``(alpha, d)`` block
the stage evolves ``pad`` extra converged modes beyond each end of the
``kappa`` axis (same solver, same endpoint), differentiates ``ln Ps`` by centred
finite differences in ``ln kappa`` (default seven-point stencil, no smoothing)
and writes ``alpha,d,kappa,Ps,ns,alpha_s`` in the canonical order.

The ``Ps`` values are copied verbatim (``repr`` round trip); the derivative
columns are the only new content.  Missing or failed amplitudes make the stage
refuse to assemble (no interpolation, no fit values).

Commands (fresh generation and post-processing use the same stage)::

    python -m vcdm_genesis.table derivatives --amplitudes OUT/amplitudes.csv --workdir OUT/derivatives \
        --output OUT/genesis_scan_table.csv --processes 18

    # post-process an existing table (Ps preserved, derivative columns regenerated):
    python -m vcdm_genesis.table derivatives --amplitudes genesis_scan_table.csv --workdir out/deriv \
        --output out/genesis_scan_table_rederived.csv
"""
from __future__ import annotations

import csv
import hashlib
import json
import os
import time
from pathlib import Path

import numpy as np

from . import __version__
from .derivatives import derivative_columns, derivatives_uniform, noise_budget
from .modes import SolverConfig, X_FINAL_PAPER
from .table import (_atomic_write_text, audit_records, keys_from_points, read_chunks, read_manifest,
                    run_amplitudes)


def read_amplitudes(path: Path):
    """Return ``(rows, axes)``; rows keep the stored ``Ps`` strings for verbatim preservation."""
    rows = []
    with open(path, newline="", encoding="utf-8") as fh:
        rd = csv.DictReader(fh)
        if not {"alpha", "d", "kappa", "Ps"} <= set(rd.fieldnames or []):
            raise ValueError("amplitude table needs columns alpha,d,kappa,Ps")
        for r in rd:
            st = r.get("status", "ok") or "ok"
            rows.append((r["alpha"], r["d"], r["kappa"], r["Ps"], st))
    alpha = sorted({float(r[0]) for r in rows}); d = sorted({float(r[1]) for r in rows}); kappa = sorted({float(r[2]) for r in rows})
    return rows, {"alpha": alpha, "d": d, "kappa": kappa}


def check_log_uniform(kappa):
    l = np.log(np.asarray(kappa, dtype=float))
    dl = np.diff(l)
    h = float(dl.mean())
    if len(l) < 7 or not np.allclose(dl, h, rtol=1e-8, atol=0.0):
        raise ValueError("kappa axis must be log-uniform with at least 7 points")
    return h


def pad_points(axes, h, pad):
    K = axes["kappa"]
    pts = []
    for a in axes["alpha"]:
        for dd in axes["d"]:
            for j in range(pad, 0, -1):
                pts.append((a, dd, K[0] * float(np.exp(-j * h))))
            for j in range(1, pad + 1):
                pts.append((a, dd, K[-1] * float(np.exp(j * h))))
    return pts


def run_derivative_stage(amplitudes: Path, workdir: Path, output: Path, processes: int, x_final: float = X_FINAL_PAPER,
                         rtol: float = SolverConfig.rtol, stencil: int = 7, chunk_size: int = 500, delta: float = 2e-9) -> dict:
    t0 = time.perf_counter()
    workdir = Path(workdir); workdir.mkdir(parents=True, exist_ok=True)
    rows, axes = read_amplitudes(Path(amplitudes))
    nA, nD, nK = len(axes["alpha"]), len(axes["d"]), len(axes["kappa"])
    if len(rows) != nA * nD * nK:
        raise ValueError(f"amplitude table is not a complete {nA}x{nD}x{nK} grid ({len(rows)} rows)")
    h = check_log_uniform(axes["kappa"])
    pad = stencil // 2
    bad = [r for r in rows if r[4] != "ok" or r[3] in ("", None)]
    if bad:
        raise RuntimeError(f"{len(bad)} amplitude rows are failed/missing (e.g. {bad[0][:3]}); refusing to derive")
    # index rows
    ia = {repr(a): i for i, a in enumerate(axes["alpha"])}; idd = {repr(x): i for i, x in enumerate(axes["d"])}; ik = {repr(k): i for i, k in enumerate(axes["kappa"])}
    Ps_str = {}
    L = np.full((nA, nD, nK), np.nan)
    for a, dd, k, ps, st in rows:
        i, j, m = ia[repr(float(a))], idd[repr(float(dd))], ik[repr(float(k))]
        Ps_str[(i, j, m)] = ps
        L[i, j, m] = np.log(float(ps))
    if not np.all(np.isfinite(L)):
        raise RuntimeError("non-finite log-power in the amplitude table")
    # pad modes (resumable amplitude stage on explicit points)
    pts = pad_points(axes, h, pad)
    key_spec = {"kind": "points", "points": pts, "source": f"pads for {amplitudes.name}: {pad} per side, h={h}"}
    cfg = SolverConfig(rtol=rtol)
    pads_dir = workdir / "pads"
    man = run_amplitudes(pads_dir, keys_from_points(pts), key_spec, x_final, cfg, processes, chunk_size=chunk_size)
    aud = audit_records(pads_dir, len(pts))
    if not aud["complete_and_clean"]:
        raise RuntimeError(f"pad modes incomplete or failed: {aud['n_failed']} failed, {aud['n_missing']} missing")
    recs = read_chunks(pads_dir)
    Lpad = np.array([np.log(recs[i]["Ps"]) for i in range(len(pts))]).reshape(nA, nD, 2 * pad)
    # derivatives
    ns = np.full((nA, nD, nK), np.nan); als = np.full((nA, nD, nK), np.nan)
    ns5 = np.full((nA, nD, nK), np.nan); als5 = np.full((nA, nD, nK), np.nan)
    kappa = np.asarray(axes["kappa"])
    for i in range(nA):
        for j in range(nD):
            lo, hi = Lpad[i, j, :pad], Lpad[i, j, pad:]
            ns[i, j], als[i, j] = derivative_columns(kappa, L[i, j], lo, hi, stencil)
            # five-point comparison on the same extended data (diagnostic only)
            l = np.log(kappa)
            l_ext = np.concatenate([l[0] - h * np.arange(pad, 0, -1), l, l[-1] + h * np.arange(1, pad + 1)])
            L_ext = np.concatenate([lo, L[i, j], hi])
            d1, d2, valid = derivatives_uniform(l_ext, L_ext, 5)
            ns5[i, j] = 1.0 + d1[pad:-pad]; als5[i, j] = d2[pad:-pad]
    if not (np.all(np.isfinite(ns)) and np.all(np.isfinite(als))):
        raise RuntimeError("non-finite derivative")
    # write final table (canonical order, Ps verbatim)
    output = Path(output)
    tmp = output.with_name(output.name + ".tmp")
    with open(tmp, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["alpha", "d", "kappa", "Ps", "ns", "alpha_s"])
        for i, a in enumerate(axes["alpha"]):
            for j, dd in enumerate(axes["d"]):
                for m, k in enumerate(axes["kappa"]):
                    w.writerow([repr(a), repr(dd), repr(k), Ps_str[(i, j, m)], repr(float(ns[i, j, m])), repr(float(als[i, j, m]))])
    os.replace(tmp, output)
    manifest = {
        "stage": "derivatives", "package_version": __version__, "input_amplitudes": str(amplitudes),
        "input_amplitudes_sha256": hashlib.sha256(Path(amplitudes).read_bytes()).hexdigest(),
        "output": str(output), "output_sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
        "grid": {"n_alpha": nA, "n_d": nD, "n_kappa": nK, "h_ln_kappa": h},
        "method": f"centred {stencil}-point finite differences of ln Ps in ln kappa; {pad} extra converged modes per side per (alpha,d); no smoothing",
        "pad_modes": {"n": len(pts), "x_final": x_final, "rtol": rtol, "dir": str(pads_dir), "fingerprint": man["fingerprint"], "solver_config": cfg.to_dict()},
        "noise_budget": noise_budget(delta, h, stencil),
        "five_point_vs_seven_point": {"max_abs_diff_ns": float(np.max(np.abs(ns - ns5))), "max_abs_diff_alpha_s": float(np.max(np.abs(als - als5))),
                                      "note": "truncation-order consistency diagnostic on the same data"},
        "ranges": {"ns": [float(ns.min()), float(ns.max())], "alpha_s": [float(als.min()), float(als.max())]},
        "Ps_preserved_verbatim": True, "seconds": time.perf_counter() - t0,
    }
    _atomic_write_text(workdir / "derivatives_manifest.json", json.dumps(manifest, indent=2) + "\n")
    return manifest
